version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 1
    labels:
      - "dependencies"
    groups:
      development-version-updates:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-version-updates:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: "security-updates"
        update-types:
          - "minor"
          - "patch"
